### ISSUE TITLE
Error when starting model_work

### ISSUE THREAD

**Issue by Jun-Howie** [ictnlp/LLaMA-Omni#11]
(base) root@autodl-container-aa9a42a072-5939b670:~/autodl-tmp# conda activate llama-omni 
(llama-omni) root@autodl-container-aa9a42a072-5939b670:~/autodl-tmp# python -m omni_speech.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path /root/autodl-tmp/Llama-3.1-8B-Omni --model-name Llama-3.1-8B-Omni --s2s
2024-09-14 20:18:54 | INFO | model_worker | args: Namespace(host='0.0.0.0', port=40000, worker_address='http://localhost:40000', controller_address='http://localhost:10000', model_path='/root/autodl-tmp/Llama-3.1-8B-Omni', model_base=None, model_name='Llama-3.1-8B-Omni', device='cuda', limit_model_concurrency=5, stream_interval=1, no_register=False, load_8bit=False, load_4bit=False, use_flash_attn=False, input_type='mel', mel_size=128, s2s=True, is_lora=False)
2024-09-14 20:18:54 | ERROR | stderr | Traceback (most recent call last):
2024-09-14 20:18:54 | ERROR | stderr |   File "/root/miniconda3/envs/llama-omni/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-09-14 20:18:54 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-09-14 20:18:54 | ERROR | stderr |   File "/root/miniconda3/envs/llama-omni/lib/python3.10/runpy.py", line 86, in _run_code
2024-09-14 20:18:54 | ERROR | stderr |     exec(code, run_globals)
2024-09-14 20:18:54 | ERROR | stderr |   File "/root/autodl-tmp/LLaMA-Omni/omni_speech/serve/model_worker.py", line 277, in <module>
2024-09-14 20:18:54 | ERROR | stderr |     worker = ModelWorker(args.controller_address,
2024-09-14 20:18:54 | ERROR | stderr |   File "/root/autodl-tmp/LLaMA-Omni/omni_speech/serve/model_worker.py", line 83, in __init__
2024-09-14 20:18:54 | ERROR | stderr |     self.tokenizer, self.model, self.context_len = load_pretrained_model(
2024-09-14 20:18:54 | ERROR | stderr |   File "/root/autodl-tmp/LLaMA-Omni/omni_speech/model/builder.py", line 79, in load_pretrained_model
2024-09-14 20:18:54 | ERROR | stderr |     model = model_cls.from_pretrained(
2024-09-14 20:18:54 | ERROR | stderr |   File "/root/miniconda3/envs/llama-omni/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3798, in from_pretrained
2024-09-14 20:18:54 | ERROR | stderr |     model = cls(config, *model_args, **model_kwargs)
2024-09-14 20:18:54 | ERROR | stderr |   File "/root/autodl-tmp/LLaMA-Omni/omni_speech/model/language_model/omni_speech2s_llama.py", line 25, in __init__
2024-09-14 20:18:54 | ERROR | stderr |     super().__init__(config)
2024-09-14 20:18:54 | ERROR | stderr |   File "/root/autodl-tmp/LLaMA-Omni/omni_speech/model/language_model/omni_speech_llama.py", line 46, in __init__
2024-09-14 20:18:54 | ERROR | stderr |     self.model = OmniSpeechLlamaModel(config)
2024-09-14 20:18:54 | ERROR | stderr |   File "/root/autodl-tmp/LLaMA-Omni/omni_speech/model/language_model/omni_speech_llama.py", line 38, in __init__
2024-09-14 20:18:54 | ERROR | stderr |     super(OmniSpeechLlamaModel, self).__init__(config)
2024-09-14 20:18:54 | ERROR | stderr |   File "/root/autodl-tmp/LLaMA-Omni/omni_speech/model/omni_speech_arch.py", line 32, in __init__
2024-09-14 20:18:54 | ERROR | stderr |     self.speech_encoder = build_speech_encoder(config)
2024-09-14 20:18:54 | ERROR | stderr |   File "/root/autodl-tmp/LLaMA-Omni/omni_speech/model/speech_encoder/builder.py", line 7, in build_speech_encoder
2024-09-14 20:18:54 | ERROR | stderr |     return WhisperWrappedEncoder.load(config)
2024-09-14 20:18:54 | ERROR | stderr |   File "/root/autodl-tmp/LLaMA-Omni/omni_speech/model/speech_encoder/speech_encoder.py", line 26, in load
2024-09-14 20:18:54 | ERROR | stderr |     encoder = whisper.load_model(name=model_config.speech_encoder, device='cpu').encoder
2024-09-14 20:18:54 | ERROR | stderr |   File "/root/miniconda3/envs/llama-omni/lib/python3.10/site-packages/whisper/__init__.py", line 139, in load_model
2024-09-14 20:18:54 | ERROR | stderr |     raise RuntimeError(
2024-09-14 20:18:54 | ERROR | stderr | RuntimeError: Model models/speech_encoder/large-v3.pt not found; available models = ['tiny.en', 'tiny', 'base.en', 'base', 'small.en', 'small', 'medium.en', 'medium', 'large-v1', 'large-v2', 'large-v3', 'large']

The models/speech_encoder folder contains large-v3.pt.
![image](https://github.com/user-attachments/assets/e0068993-a0a3-4fe3-823d-3eec92491c07)

**Comment by Poeroz** [comment]
It seems that your path is `model/speech_encoder` instead of `models/speech_encoder`. Please correct it accordingly.

**Comment by Jun-Howie** [comment]
You're right. Thank you.
