### ISSUE TITLE
'_flash_supports_window_size' is not defined

### ISSUE THREAD

**Issue by boji123** [ictnlp/LLaMA-Omni#32]
2024-09-27 14:38:56 | ERROR | stderr |     _flash_supports_window_size and sliding_window is not None and key_states.shape[1] > sliding_window
2024-09-27 14:38:56 | ERROR | stderr | NameError: name '_flash_supports_window_size' is not defined

**Comment by maugomez77** [comment]
any update on this one?

**Comment by NghiaaPD** [comment]
same issue :)))

**Comment by Domanmaker** [comment]
me too

**Comment by UltraEval** [comment]
`flash_attn` is too lower, must be >=2.1.0 if use CUDA
![image](https://github.com/user-attachments/assets/630ccc65-9ee1-4d8c-993b-9f6e83a21e75)
better download whl from https://github.com/Dao-AILab/flash-attention/releases, then pip install

**Comment by wu-wen-zhou** [comment]
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-j7xyhe9c/flash-attn_d871209e23f84ff78b283e03c2e57230/setup.py", line 156, in <module>
          _, bare_metal_version = get_cuda_bare_metal_version(CUDA_HOME)
        File "/tmp/pip-install-j7xyhe9c/flash-attn_d871209e23f84ff78b283e03c2e57230/setup.py", line 82, in get_cuda_bare_metal_version
          raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
        File "/root/miniconda3/envs/llama-omni/lib/python3.10/subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/root/miniconda3/envs/llama-omni/lib/python3.10/subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/root/miniconda3/envs/llama-omni/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/root/miniconda3/envs/llama-omni/lib/python3.10/subprocess.py", line 1863, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/cuda/bin/nvcc'

When I run the command pip install flash-attn --no-build-isolation, it gives the error mentioned above. And I can't find '/usr/local/cuda/bin/nvcc'

**Comment by Sakkana** [comment]
> Preparing metadata (setup.py) ... error准备元数据（setup.py）...错误 error: subprocess-exited-with-error错误：子进程因错误而退出
> 
> × python setup.py egg_info did not run successfully.× python setup.py egg_info 未成功运行。 │ exit code: 1│ 退出代码：1 ╰─> [22 lines of output]╰─> [22行输出] fatal: not a git repository (or any of the parent directories): .git致命：不是 git 存储库（或任何父目录）：.git Traceback (most recent call last):回溯（最近一次调用最后一次）： File "", line 2, in 文件“”，第 2 行，位于 File "", line 34, in 文件“”，第 34 行，位于 File "/tmp/pip-install-j7xyhe9c/flash-attn_d871209e23f84ff78b283e03c2e57230/setup.py", line 156, in 文件“/tmp/pip-install-j7xyhe9c/flash-attn_d871209e23f84ff78b283e03c2e57230/setup.py”，第 156 行，位于 _, bare_metal_version = get_cuda_bare_metal_version(CUDA_HOME)_，bare_metal_version = get_cuda_bare_metal_version（CUDA_HOME） File "/tmp/pip-install-j7xyhe9c/flash-attn_d871209e23f84ff78b283e03c2e57230/setup.py", line 82, in get_cuda_bare_metal_version文件“/tmp/pip-install-j7xyhe9c/flash-attn_d871209e23f84ff78b283e03c2e57230/setup.py”，第 82 行，位于 get_cuda_bare_metal_version raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)raw_output = subprocess.check_output（[cuda_dir +“/ bin / nvcc”，“-V”]，universal_newlines = True） File "/root/miniconda3/envs/llama-omni/lib/python3.10/subprocess.py", line 421, in check_output文件“/root/miniconda3/envs/llama-omni/lib/python3.10/subprocess.py”，第 421 行，位于 check_output 中 return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,返回运行（*popenargs，stdout=PIPE，timeout=timeout，check=True， File "/root/miniconda3/envs/llama-omni/lib/python3.10/subprocess.py", line 503, in run文件“/root/miniconda3/envs/llama-omni/lib/python3.10/subprocess.py”，第 503 行，正在运行 with Popen(*popenargs, **kwargs) as process:使用 Popen(*popenargs, **kwargs) 作为流程： File "/root/miniconda3/envs/llama-omni/lib/python3.10/subprocess.py", line 971, in **init**文件“/root/miniconda3/envs/llama-omni/lib/python3.10/subprocess.py”，第 971 行，在 **init 中** self._execute_child(args, executable, preexec_fn, close_fds,self._execute_child（args，可执行文件，preexec_fn，close_fds， File "/root/miniconda3/envs/llama-omni/lib/python3.10/subprocess.py", line 1863, in _execute_child文件“/root/miniconda3/envs/llama-omni/lib/python3.10/subprocess.py”，第 1863 行，位于 _execute_child raise child_exception_type(errno_num, err_msg, err_filename)引发 child_exception_type（errno_num、err_msg、err_filename） FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/cuda/bin/nvcc'FileNotFoundError：[Errno 2] 没有这样的文件或目录：'/usr/local/cuda/bin/nvcc'
> 
> When I run the command pip install flash-attn --no-build-isolation, it gives the error mentioned above. And I can't find '/usr/local/cuda/bin/nvcc'当我运行命令 pip install flash-attn --no-build-isolation 时，出现了上述错误。而且我找不到“/usr/local/cuda/bin/nvcc”

装一下 nvcc
