### ISSUE TITLE
报错求助：找不到config.json文件

### ISSUE THREAD

**Issue by Enermy** [ictnlp/LLaMA-Omni#40]
我已经下载了模型，报错说找不到config.json文件。请问各位大佬是路径问题还是什么问题？
2024-10-09 23:13:19 | ERROR | stderr | OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like Llama-3.1-8B-Omni is not the path to a directory containing a file named config.json.
2024-10-09 23:13:19 | ERROR | stderr | Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
![微信图片_20241009233544](https://github.com/user-attachments/assets/ef624c4d-535c-44d5-b87e-e1c15547db28)

**Comment by Enermy** [comment]
这个解决了，在推理时出现了另外一个bug：2024-10-10 00:26:25 | ERROR | stderr | Traceback (most recent call last):
2024-10-10 00:26:25 | ERROR | stderr |   File "/home/jiangsiyuan/anaconda3/envs/llama-omni/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
2024-10-10 00:26:25 | ERROR | stderr |     response = await route_utils.call_process_api(
2024-10-10 00:26:25 | ERROR | stderr |   File "/home/jiangsiyuan/anaconda3/envs/llama-omni/lib/python3.10/site-packages/gradio/route_utils.py", line 321, in call_process_api
2024-10-10 00:26:25 | ERROR | stderr |     output = await app.get_blocks().process_api(
2024-10-10 00:26:25 | ERROR | stderr |   File "/home/jiangsiyuan/anaconda3/envs/llama-omni/lib/python3.10/site-packages/gradio/blocks.py", line 1931, in process_api
2024-10-10 00:26:25 | ERROR | stderr |     inputs = await self.preprocess_data(
2024-10-10 00:26:25 | ERROR | stderr |   File "/home/jiangsiyuan/anaconda3/envs/llama-omni/lib/python3.10/site-packages/gradio/blocks.py", line 1662, in preprocess_data
2024-10-10 00:26:25 | ERROR | stderr |     processed_input.append(block.preprocess(inputs_cached))
2024-10-10 00:26:25 | ERROR | stderr |   File "/home/jiangsiyuan/anaconda3/envs/llama-omni/lib/python3.10/site-packages/gradio/components/audio.py", line 231, in preprocess
2024-10-10 00:26:25 | ERROR | stderr |     sample_rate, data = processing_utils.audio_from_file(temp_file_path)
2024-10-10 00:26:25 | ERROR | stderr |   File "/home/jiangsiyuan/anaconda3/envs/llama-omni/lib/python3.10/site-packages/gradio/processing_utils.py", line 546, in audio_from_file
2024-10-10 00:26:25 | ERROR | stderr |     raise RuntimeError(msg) from e
2024-10-10 00:26:25 | ERROR | stderr | RuntimeError: Cannot load audio from file: `ffprobe` not found. Please install `ffmpeg` in your system to use non-WAV audio file formats and make sure `ffprobe` is in your PATH.

**Comment by world1tree** [comment]
安装ffmpeg。如果没有权限的话，官网下载源码编译安装，然后把可执行文件目录(该目录中包含`ffmpeg`/`ffprobe`等)加到`PATH`路径中
